# DO NOT EDIT THIS FILE!
#
# This file is generated from the CDP specification. If you need to make
# changes, edit the generator and regenerate all of the modules.

from . import (
    accessibility,
    browser,
    debugger,
    dom,
    emulation,
    fetch,
    input_,
    inspector,
    io,
    log,
    network,
    page,
    runtime,
    security,
    storage,
    target,
 )
