/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'intro',
        'installation',
        'quickstart',
        'first_script',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core_concepts',
        'selectors',
        'interactions',
        'waiting',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Features',
      items: [
        'network',
        'stealth',
        'ai_features',
        'advanced_cdp',
        'async_patterns',
      ],
    },
    {
      type: 'category',
      label: 'Production',
      items: [
        'production',
        'modular_architecture',
      ],
    },
  ],
};

export default sidebars;
